name: Build project + unit test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, lint, test
      run: |
        npm ci
        npm run build
    - name: move to function, init & run test
      run: |
        cd functions
        npm ci
        npm run build
